defaults:
  - _self_

seed: 47

wandb:
  project: forge-v1.5
  run_id: null

checkpoint_path: null

model:
  _target_: forge.models._dit.FlagDiT
  input_dim: 1280
  hidden_dim: 1280
  mlp_ratio: 2.0
  num_heads: 20
  num_layers: 20
  conditioning_dropout: 0.3

lightning_module:
  ema_decay: 0.9999
  learning_rate: 1e-4

validation:
  fid_reference_path: /new-stg/home/young/forge_v1_old/data/10k_ref_8_8.pt
  t_steps: 50
  guidance_scale: 3.0
  fid_sample_size: 10000

trainer:
  max_steps: 2_000_000
  limit_val_batches: 50
  accelerator: auto
  devices: auto
  precision: 32
  log_every_n_steps: 1
  strategy: ddp

datamodule:
  train_csv_path: /new-stg/home/young/forge_v1_old/data/train_hq_x_removed_swapped.csv.gz
  val_csv_path: /new-stg/home/young/forge_v1_old/data/val_hq_swapped.csv.gz
  seq_len_path: /new-stg/home/young/forge_v1_old/data/protein_lengths.csv.gz
  lmdb_path: /scratch/young/raygun_hq_8_8_numpy.lmdb
  batch_size: 500
  num_workers: 1
  pin_memory: true
  prefetch_factor: 4
  persistent_workers: true